name: blog rendering via gha

on:
  push:
    paths:
      - "index.md"
      - "posts/**"

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Timestamp
        run: date --rfc-3339=seconds > lastBuild.txt

      - name: Render Posts
        run: |
          docker pull pandoc/core:latest
          for post in posts/*_*.md; do
            [ -e "$post" ] || continue
            base=$(basename "$post" .md)
            docker run --volume "`pwd`:/data" --entrypoint "pandoc" pandoc/core:latest -s "$post" -o "posts/${base}.html" -c style.css
          done

      - name: Update index.md with posts list
        run: |
          # Generate posts list from posts markdown files
          posts_list=$(for post in $(ls posts/*_*.md | sort -r); do
            base=$(basename "$post" .md)
            title=$(head -n 1 "$post" | sed 's/# //')
            echo "- [$title](posts/${base}.html)"
          done)
          echo "$posts_list"
          # Replace content between markers <!-- POSTS START --> and <!-- POSTS END -->
          perl -0777 -pe 's/(<!-- POSTS START -->).*(<!-- POSTS END -->)/$1\n'"$posts_list"'\n$2/s' index.md > index_temp.md
          mv index_temp.md index.md

      - name: Render index.md
        run: |
          docker run --volume "`pwd`:/data" --entrypoint "pandoc" pandoc/core:latest -s index.md -o index.html -c style.css

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          push: true
          default_author: github_actions
